### ISSUE TITLE
Face Cards Not Being Assigned Value as Expected 

### ISSUE THREAD

**Issue by AlanRice93** [AlanRice93/BlackJack#1]
## User Story 
- As a dealer, I want to be able to build a deck and assign value to each card created

## Test Statement 
 - When I call any card from the deck[] array, it should return a card Object with a suit, value(worth), and symbol(king, "2", etc)

## Context
- I have successfully assigned value to all of the number cards. I therefore attempted to use the same syntax with the face cards to no avail. I am attempting to set all of their values to 10 through a conditional statement and cannot figure out why it's not working.  
- I have tried isolating each face value, breaking up the function, removing the conditional and restarting, using 2 ==, and moving the order of conditional statements. 
 ## Error Message
- the error message isn't really an error, but rather it's assinging a value of Nan when I want it to be 10;
```
Card {symbol: "Queen", suit: "Club", worth: NaN}
```

**Comment by iiVi** [comment]
Helped in person.
